const genres = [
    '4-Koma',
    'Action',
    'Adventure',
    'Comedy',
    'Cooking',
    'Crime',
    'Demons',
    'Drama',
    'Ecchi',
    'Fantasy',
    'Game',
    'Gender Bender',
    'Gore',
    'Harem',
    'Historical',
    'Horror',
    'Isekai',
    'Josei',
    'Life',
    'Magic',
    'Manhua',
    'Manhwa',
    'Martial Arts',
    'Mature',
    'Mecha',
    'Medical',
    'Military',
    'Monsters',
    'Music',
    'Mystery',
    'Namaikizakari',
    'One Shot',
    'Overpower',
    'Parodi',
    'Police',
    'Psychological',
    'Reincarnatio',
    'Reincarnation',
    'Romance',
    'School',
    'School life',
    'Sci-fi',
    'Seinen',
    'Shotacon',
    'Shoujo',
    'Shoujo Ai',
    'Shounen',
    'Shounen Ai',
    'Slice of Life',
    'Sport',
    'Sports',
    'Super Power',
    'Supernatural',
    'Thriller',
    'Tragedy',
    'Urban',
    'Vampire',
    'Vampires',
    'Villainess',
    'Webtoons',
    'Yuri',
]

exports.genres = genres
